# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Pothole_detection',
                'doc_host': 'https://fevzikilas.github.io',
                'git_url': 'https://github.com/fevzikilas/Pothole_detection',
                'lib_path': 'Pothole_detection'},
  'syms': {'Pothole_detection.core': {'Pothole_detection.core.foo': ('core.html#foo', 'Pothole_detection/core.py')}}}
